### ISSUE TITLE
Bug: `ctx.effect` 在子 plugin 里失效（没有调用 dispose）

### ISSUE THREAD

**Issue by dingyi222666** [cordisjs/cordis#8]
复现测试代码：

```ts
test('ctx.effect() with plugin', async () => {
    const root = new Context()
    const items = [0, 1, 2, 3]

    const dispose = () => {
      items.length = 0
    }

    const apply = (ctx: Context) => {
      ctx.on(event, () => {
        ctx.effect(() => dispose)
      })
    }

    root.plugin(apply)

    await root.lifecycle.flush()

    root.emit(event)
    root.registry.delete(apply)

    expect(items).to.have.length(0)
 })
```

预期结果：dispose 被调用，items 内没有元素。
实际结果：dispose 没有被调用，items 没有发生变化。

复现版本： https://github.com/cordiverse/cordis/commit/fd408a422375972b4ff02a9647063919d055b133 (从 github 克隆）

其他事项：我克隆了在 https://github.com/cordiverse/cordis/commit/86e0b804427222a77baf49b9d6d8067f447cdb67 提交之前的代码库，没有复现该错误，推测是[该行代码](https://github.com/cordiverse/cordis/commit/86e0b804427222a77baf49b9d6d8067f447cdb67#diff-4295ebb25857ae631a6be3b9af5abd55877e66e0ce12598deeb307bcb0a501e6R97)可能有什么问题。

考虑到这行代码的作用，直接去掉判断可能不合理，故我没有直接提 PR 把判断逻辑去掉（

**Comment by shigma** [comment]
确实看起来有问题，感谢如此详尽的反馈。
